---
title: Setting up a GitHub blog for R users
author: Collin Erickson
date: '2017-05-26'
slug: ''
categories: []
tags: []
---

A while back I tried to set up a GitHub blog following instructions using Jekyll and Ruby, which seems to be the recommended method by [GitHub](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/). I had lots of trouble following tutorials and getting it to work, and eventually abandoned it.

Recently I tried again, after finding out that I can do it through RStudio, using the R package [blogdown](https://bookdown.org/yihui/blogdown/).
I followed the instructions provided by [Robert Myles](http://robertmyles.github.io/2017/02/01/how-to-make-a-github-pages-blog-with-rstudio-and-hugo/), and it seems to be working fine so far.
This is much better for me, seeing as I am a heavy RStudio user.
I still need to get it personalized and put something useful on here, but I've completed the hardest part.

If you are an R user you should be using Rmarkdown to create documents with R code embedded,
and you should use blogdown to create your blog posts since it makes the entire process very easy.