---
title: Running Python in RStudio with reticulate
author: Collin Erickson
date: '2018-06-25'
slug: running-python-in-rstudio-with-reticulate
categories: []
tags: [RStudio, Python]
---

One of the main reasons I strongly prefer R to Python is that 
RStudio is far better than all Python IDEs I have used.
I usually use Spyder for my Python IDE, but it has a lot
of shortcomings compared to RStudio.

RStudio has added some Python support, for example in Rmarkdown
files in the past.
This week I discovered the R package reticulate which is closely
integrated with RStudio and lets you run Python code more easily
in RStudio.
[This blog post](https://blog.rstudio.com/2018/03/26/reticulate-r-interface-to-python/)
gives a great overview of how it works with examples.

Examples here.

When I have two Python chunks in an Rmarkdown file, the variables are
shared between them as expected.
But if I try to run the cells one at a time in RStudio,
the second chunk won't have variables from the first chunk.

Shortcomings: not full Python IDE, likely won't ever since R is focus.
No text highlighting or autosuggest for Python files in RStudio.
